W5D1/music_app1/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users
  resource :session 
end

W5D1/music_app1/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

W5D1/music_app1/app/models/user.rb
class User < ApplicationRecord
  validates :password_digest, :email, :session_token, presence: true, uniqueness: true
  validates :password, length: { minimum: 6, allow_nil: true}

  after_initialize :ensure_session_token
  attr_reader :password

  def generate_session_token
    SecureRandom.urlsafe_base64
  end

  def self.find_by_credentials(email,password)
    @user = User.find_by(email: email)

    if @user.is_password?(password)
      @user
    else
      nil
    end
  end

  def ensure_session_token
    self.session_token ||= generate_session_token
  end

  def reset_session_token
    self.session_token = generate_session_token
    self.save!
    self.session_token
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end
end

W5D1/music_app1/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # protect_from_forgery with: :exception
  helper_method :current_user, :logged_in?, :login_user

  def current_user
    return nil unless session[:session_token]
    @current_user ||= User.find_by_session_token(session[:session_token])
  end

  def logged_in?
    !!current_user
  end

  def login_user(user)
    session[:session_token] = user.reset_session_token
  end
end

W5D1/music_app1/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    render :new
  end

  def create
    @user = User.find_by_credentials(
      params[:user][:email],
      params[:user][:password]
    )

    if @user.nil?
      flash.now[:errors] = ['Invalid credentials']
      render :new
    else
      login_user(@user)
      redirect_to user_url(@user.id)
    end
  end

  def destroy
    current_user.reset_session_token
    session[:session_token] = nil
    redirect_to new_session_url
  end
end

W5D1/music_app1/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
    render :new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      login_user(@user)
      redirect_to user_url(@user.id)
    else
      flash.now[:errors] = @user.errors.full_messages
    end
  end

  def index
    @users = User.all
    render :index
  end

  def show
    render :show
  end

  private
  def user_params
    params.require(:user).permit(:email, :password)
  end
end

W5D1/music_app1/app/helpers/application_helper.rb
module ApplicationHelper
end

W5D1/music_app1/app/helpers/sessions_helper.rb
module SessionsHelper
end

W5D1/music_app1/app/helpers/users_helper.rb
module UsersHelper
end

W5D1/music_app1/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MusicApp1</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>

    <% if logged_in? %>
        <%= button_to 'Logout', session_url, method: :delete %>
        <p>Logged In as <%= current_user.email %></p>
    <% else %>
      <%= button_to 'Sign In', new_session_url, method: :get %>
      <%= button_to 'Sign Up', new_user_url, method: :get %>

    <% end %>

    <%= yield %>
  </body>
</html>

W5D1/music_app1/app/views/users/index.html.erb
<h1>Users</h1>

<ul>
  <% @users.each do |user| %>
  <li><%= user.email %></li>
  <% end %>
</ul>

W5D1/music_app1/app/views/users/new.html.erb
<h1>Sign Up</h1>

<form action="<%= users_url %>" method="post">
  <input type="hidden" name="authenticity_token" value="<%=form_authenticity_token%>">

  <label>Email</label>
    <input type="text" name="user[email]" value="">

  <label>Password
    <input type="password" name="user[password]" value="">
  </label>

  <input type="submit" name="" value="Submit">

</form>

W5D1/music_app1/app/views/users/show.html.erb
<h1>Hey there.</h1>
<ul>
  <li><%= current_user.email %></li>
</ul>